version: "3"
networks:
  micro-net:
    driver: bridge
    name: micro-net
volumes:
  api-gateway-node-modules:
  booking-service-node-modules:
  flight-service-node-modules:
  notification-service-node-modules:
services:
  api-gateway:
    build: ./API_Gateway
    networks:
      - micro-net
    ports:
      - "5000:5000"
    volumes:
      - ./API_Gateway:/FMS/api-gateway
      - api-gateway-node-modules:/FMS/api-gateway/node_modules

  booking-service:
    build: ./Booking_Service
    networks:
      - micro-net
    ports:
      - "5001:5001"
    volumes:
      - ./Booking_Service:/FMS/booking-service
      - booking-service-node-modules:/FMS/booking-service/node_modules

  flight-service:
    build: ./Flight_Service
    networks:
      - micro-net
    ports: 
      - "5002:5002"
    volumes:
      - ./Flight_Service:/FMS/flight-service
      - flight-service-node-modules:/FMS/flight-service/node_modules

  notification-service:
    build: ./Notification_Service
    networks:
      - micro-net
    ports: 
      - "5003:5003"
    volumes:
      - ./Notification_Service:/FMS/notification-service
      - notification-service-node-modules:/FMS/notification-service/node_modules
  
    
